version: '3.3'

services:
  traefik:
    image: traefik:3.1.2
    restart: always
    container_name: traefik
    ports:
      - 443:443
      - 80:80
    volumes:
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "./traefik/dynamic:/root/dynamic"
      - "/root/cert:/root/cert"
      - "./traefik/log:/var/log/"
